import Head from "next/head";

const AppHead = () => {
  return (
    <Head>
      <title>Frontbook</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export { AppHead };
