import { FC, ReactNode } from "react";
import Link from "next/link";
import Head from "next/head";
import React from "react";
import styles from "../styles/Home.module.css";

const Layout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <header>
          <Link href="/">
            <a>Home</a>
          </Link>
        </header>
        <div className="page-content">{children}</div>

        <footer className={styles.footer}>Footer</footer>
      </div>
    </>
  );
};

export default Layout;
